---
- name: Configure Dev Environment Servers
  hosts: dev
  become: true
  vars:
    env_name: dev  
    timezone: America/New_York
  
  roles:
    - common
    - monitoring
    - webserver
  
  vars_files:
    - "vars/{{ env_name }}/main.yml"
